SELECT DATE_FORMAT(O.SALES_DATE,'%Y-%m-%d') SALES_DATE, O.PRODUCT_ID, O.USER_ID, O.SALES_AMOUNT
FROM ONLINE_SALE O
WHERE DATE_FORMAT(O.SALES_DATE,'%Y-%m') = '2022-03'

UNION ALL

SELECT DATE_FORMAT(f.SALES_DATE,'%Y-%m-%d') SALES_DATE, F.PRODUCT_ID, NULL AS USER_ID, F.SALES_AMOUNT
FROM OFFLINE_SALE F
WHERE DATE_FORMAT(F.SALES_DATE,'%Y-%m') = '2022-03'
ORDER BY SALES_DATE, PRODUCT_ID, USER_ID