WITH RECURSIVE H AS (
    SELECT 0 HOUR
    UNION ALL
    SELECT HOUR + 1
    FROM H
    WHERE HOUR < 23
)

SELECT H.HOUR, COUNT(O.ANIMAL_ID) AS 'COUNT'
FROM H
    LEFT JOIN ANIMAL_OUTS O
    ON H.HOUR = DATE_FORMAT(O.DATETIME, "%H")
GROUP BY H.HOUR
ORDER BY H.HOUR;