SELECT B.WRITER_ID, S.NICKNAME, SUM(PRICE) AS TOTAL_SALES
FROM USED_GOODS_BOARD B
    JOIN USED_GOODS_USER S
    ON B.WRITER_ID = S.USER_ID
WHERE B.STATUS = 'DONE'
GROUP BY WRITER_ID
HAVING SUM(PRICE) >= 700000
ORDER BY TOTAL_SALES;